[book]
authors = ["emary"]
language = "zh"
multilingual = false
src = "src"
title = "emary'blog"
description= "emary'blog"

[output.html]
# defaulr dark theme
default-theme = "navy"
# for Chinese search
additional-js = ["assets/fzf.umd.js", "assets/elasticlunr.js", "assets/reference.js", "assets/highlight.js", "theme/pagetoc.js"]
additional-css = ["assets/utils.css", "theme/pagetoc.css"]

# set open math support
mathjax-support = true
